# Generated by Django 3.1.1 on 2020-09-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_name', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('index_name', models.SmallIntegerField(choices=[(0, 'その他'), (1, 'あ行'), (2, 'か行'), (3, 'さ行'), (4, 'た行'), (5, 'な行'), (6, 'は行'), (7, 'ま行'), (8, 'や行'), (9, 'ら行'), (10, 'わ行')])),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255, null=True)),
                ('address_2', models.CharField(max_length=255, null=True)),
                ('address_3', models.TextField()),
                ('telephone_number_1', models.CharField(max_length=255, null=True)),
                ('telephone_number_2', models.CharField(max_length=255, null=True)),
                ('fax_number', models.CharField(max_length=255, null=True)),
                ('mail_address', models.CharField(max_length=255, null=True)),
                ('note', models.TextField()),
                ('delete_flg', models.BooleanField(default=False)),
                ('create_user', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_name', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255, null=True)),
                ('address_2', models.CharField(max_length=255, null=True)),
                ('address_3', models.TextField()),
                ('telephone_number_1', models.CharField(max_length=255, null=True)),
                ('telephone_number_2', models.CharField(max_length=255, null=True)),
                ('fax_number', models.CharField(max_length=255, null=True)),
                ('mail_address', models.CharField(max_length=255, null=True)),
                ('note', models.TextField()),
                ('delete_flg', models.BooleanField(default=False)),
                ('create_user', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.company')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_name', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255, null=True)),
                ('address_2', models.CharField(max_length=255, null=True)),
                ('address_3', models.TextField()),
                ('telephone_number_1', models.CharField(max_length=255, null=True)),
                ('telephone_number_2', models.CharField(max_length=255, null=True)),
                ('fax_number', models.CharField(max_length=255, null=True)),
                ('mail_address', models.CharField(max_length=255, null=True)),
                ('person_role_name', models.CharField(max_length=255, null=True)),
                ('retier_flg', models.BooleanField(default=False)),
                ('retier_date', models.DateField(null=True)),
                ('note', models.TextField()),
                ('delete_flg', models.BooleanField(default=False)),
                ('create_user', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.company')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.section')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
